[build]
  publish = "."
  command = ""

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_API_KEY"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
